#!/usr/bin/env php
<?php

$container = require_once __DIR__ . '/bootstrap.php';

/* @var $compiler h4kuna\Gettext\Latte\LatteCompiler */
$compiler = $container->getService('gettextLatteExtension.compiler');
$compiler->addInclude(__DIR__ . '/../examples');
$compiler->addExclude(__DIR__ . '/../examples/example.latte');
$compiler->addInclude(__DIR__ . '/../examples');
$compiler->run();